// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID           int32          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	BusinessName string         `json:"business_name"`
	ContactName  sql.NullString `json:"contact_name"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	Address1     string         `json:"address_1"`
	Address2     sql.NullString `json:"address_2"`
	City         string         `json:"city"`
	State        string         `json:"state"`
	ZipCode      string         `json:"zip_code"`
	Terms        string         `json:"terms"`
	Discount     float64        `json:"discount"`
	Commission   float64        `json:"commission"`
	SalesRep     sql.NullString `json:"sales_rep"`
	Notes        sql.NullString `json:"notes"`
}

type CustomerLocation struct {
	ID         int32          `json:"id"`
	CustomerID int32          `json:"customer_id"`
	Address1   string         `json:"address_1"`
	Address2   sql.NullString `json:"address_2"`
	City       string         `json:"city"`
	State      string         `json:"state"`
	ZipCode    string         `json:"zip_code"`
	Phone      sql.NullString `json:"phone"`
	Notes      sql.NullString `json:"notes"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Invoice struct {
	ID                 int32         `json:"id"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
	InvoiceDate        time.Time     `json:"invoice_date"`
	OrderID            int32         `json:"order_id"`
	CustomerID         int32         `json:"customer_id"`
	CustomerLocationID sql.NullInt32 `json:"customer_location_id"`
	DueDate            time.Time     `json:"due_date"`
	Status             string        `json:"status"`
	Total              float64       `json:"total"`
}

type Order struct {
	ID                 int32          `json:"id"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	CustomerID         int32          `json:"customer_id"`
	CustomerLocationID int32          `json:"customer_location_id"`
	OrderDate          time.Time      `json:"order_date"`
	ShipDate           time.Time      `json:"ship_date"`
	Status             string         `json:"status"`
	Type               string         `json:"type"`
	Method             sql.NullString `json:"method"`
	PoNumber           sql.NullString `json:"po_number"`
	ShippingCost       float64        `json:"shipping_cost"`
	FreeShipping       bool           `json:"free_shipping"`
	ApplyToCommission  bool           `json:"apply_to_commission"`
	SalesRep           sql.NullString `json:"sales_rep"`
	Notes              sql.NullString `json:"notes"`
}

type OrderItem struct {
	ID           int32         `json:"id"`
	OrderID      int32         `json:"order_id"`
	Sku          string        `json:"sku"`
	Quantity     int32         `json:"quantity"`
	Price        float64       `json:"price"`
	Discount     float64       `json:"discount"`
	ItemTotal    float64       `json:"item_total"`
	PocketNumber sql.NullInt32 `json:"pocket_number"`
}

type Planogram struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	NumPockets int32          `json:"num_pockets"`
	Notes      sql.NullString `json:"notes"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type PlanogramCustomerLocation struct {
	ID                 int32 `json:"id"`
	PlanogramID        int32 `json:"planogram_id"`
	CustomerLocationID int32 `json:"customer_location_id"`
}

type PlanogramPocket struct {
	ID           int32         `json:"id"`
	PlanogramID  int32         `json:"planogram_id"`
	PocketNumber int32         `json:"pocket_number"`
	Category     string        `json:"category"`
	ProductID    sql.NullInt32 `json:"product_id"`
}

type Product struct {
	ID             uuid.UUID      `json:"id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Type           string         `json:"type"`
	Sku            string         `json:"sku"`
	Upc            string         `json:"upc"`
	Status         string         `json:"status"`
	Cost           float64        `json:"cost"`
	Price          float64        `json:"price"`
	Envelope       sql.NullString `json:"envelope"`
	Artist         sql.NullString `json:"artist"`
	Category       sql.NullString `json:"category"`
	ReleaseDate    sql.NullTime   `json:"release_date"`
	LastBoughtDate sql.NullTime   `json:"last_bought_date"`
	Description    sql.NullString `json:"description"`
	TextFront      sql.NullString `json:"text_front"`
	TextInside     sql.NullString `json:"text_inside"`
}

type RefreshToken struct {
	Token     string       `json:"token"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	UserID    uuid.UUID    `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type SalesRep struct {
	ID        int32          `json:"id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Status    string         `json:"status"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	Company   string         `json:"company"`
	Address1  sql.NullString `json:"address_1"`
	Address2  sql.NullString `json:"address_2"`
	City      sql.NullString `json:"city"`
	State     sql.NullString `json:"state"`
	ZipCode   sql.NullString `json:"zip_code"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Password  string    `json:"password"`
}
