// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID           int32          `json:"id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	BusinessName string         `json:"business_name"`
	ContactName  sql.NullString `json:"contact_name"`
	Email        sql.NullString `json:"email"`
	Phone        sql.NullString `json:"phone"`
	Address1     sql.NullString `json:"address_1"`
	Address2     sql.NullString `json:"address_2"`
	City         sql.NullString `json:"city"`
	State        sql.NullString `json:"state"`
	ZipCode      sql.NullString `json:"zip_code"`
	Terms        sql.NullString `json:"terms"`
	Discount     string         `json:"discount"`
	Commission   string         `json:"commission"`
	Notes        sql.NullString `json:"notes"`
}

type Order struct {
	ID                int32          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CustomerID        int32          `json:"customer_id"`
	OrderDate         time.Time      `json:"order_date"`
	ShipDate          time.Time      `json:"ship_date"`
	Status            string         `json:"status"`
	Type              string         `json:"type"`
	Method            sql.NullString `json:"method"`
	PoNumber          sql.NullString `json:"po_number"`
	ShippingCost      string         `json:"shipping_cost"`
	FreeShipping      bool           `json:"free_shipping"`
	ApplyToCommission bool           `json:"apply_to_commission"`
	Notes             sql.NullString `json:"notes"`
}

type OrderItem struct {
	ID        int32  `json:"id"`
	OrderID   int32  `json:"order_id"`
	Item      string `json:"item"`
	Quantity  int32  `json:"quantity"`
	Price     string `json:"price"`
	Discount  string `json:"discount"`
	ItemTotal string `json:"item_total"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Password  string    `json:"password"`
}
