// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, order_date, status, type, method, ship_date, po_number, shipping_cost, free_shipping, apply_to_commission, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at, updated_at, customer_id, order_date, status, type, method, ship_date, po_number, shipping_cost, free_shipping, apply_to_commission, notes
`

type CreateOrderParams struct {
	CustomerID        int32          `json:"customer_id"`
	OrderDate         time.Time      `json:"order_date"`
	Status            string         `json:"status"`
	Type              string         `json:"type"`
	Method            sql.NullString `json:"method"`
	ShipDate          time.Time      `json:"ship_date"`
	PoNumber          sql.NullString `json:"po_number"`
	ShippingCost      string         `json:"shipping_cost"`
	FreeShipping      bool           `json:"free_shipping"`
	ApplyToCommission bool           `json:"apply_to_commission"`
	Notes             sql.NullString `json:"notes"`
}

type CreateOrderRow struct {
	ID                int32          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CustomerID        int32          `json:"customer_id"`
	OrderDate         time.Time      `json:"order_date"`
	Status            string         `json:"status"`
	Type              string         `json:"type"`
	Method            sql.NullString `json:"method"`
	ShipDate          time.Time      `json:"ship_date"`
	PoNumber          sql.NullString `json:"po_number"`
	ShippingCost      string         `json:"shipping_cost"`
	FreeShipping      bool           `json:"free_shipping"`
	ApplyToCommission bool           `json:"apply_to_commission"`
	Notes             sql.NullString `json:"notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder,
		arg.CustomerID,
		arg.OrderDate,
		arg.Status,
		arg.Type,
		arg.Method,
		arg.ShipDate,
		arg.PoNumber,
		arg.ShippingCost,
		arg.FreeShipping,
		arg.ApplyToCommission,
		arg.Notes,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.OrderDate,
		&i.Status,
		&i.Type,
		&i.Method,
		&i.ShipDate,
		&i.PoNumber,
		&i.ShippingCost,
		&i.FreeShipping,
		&i.ApplyToCommission,
		&i.Notes,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteOrderStmt, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, created_at, updated_at, customer_id, order_date, ship_date, status, type, method, po_number, shipping_cost, free_shipping, apply_to_commission, notes
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int32) (Order, error) {
	row := q.queryRow(ctx, q.getOrderStmt, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.OrderDate,
		&i.ShipDate,
		&i.Status,
		&i.Type,
		&i.Method,
		&i.PoNumber,
		&i.ShippingCost,
		&i.FreeShipping,
		&i.ApplyToCommission,
		&i.Notes,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, created_at, updated_at, customer_id, order_date, ship_date, status, type, method, po_number, shipping_cost, free_shipping, apply_to_commission, notes
FROM orders
ORDER BY order_date DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.query(ctx, q.listOrdersStmt, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerID,
			&i.OrderDate,
			&i.ShipDate,
			&i.Status,
			&i.Type,
			&i.Method,
			&i.PoNumber,
			&i.ShippingCost,
			&i.FreeShipping,
			&i.ApplyToCommission,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET customer_id = $2,
    order_date = $3,
    status = $4,
    type = $5,
    method = $6,
    ship_date = $7,
    po_number = $8,
    shipping_cost = $9,
    free_shipping = $10,
    apply_to_commission = $11,
    notes = $12,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, customer_id, order_date, status, type, method, ship_date, po_number, shipping_cost, free_shipping, apply_to_commission, notes
`

type UpdateOrderParams struct {
	ID                int32          `json:"id"`
	CustomerID        int32          `json:"customer_id"`
	OrderDate         time.Time      `json:"order_date"`
	Status            string         `json:"status"`
	Type              string         `json:"type"`
	Method            sql.NullString `json:"method"`
	ShipDate          time.Time      `json:"ship_date"`
	PoNumber          sql.NullString `json:"po_number"`
	ShippingCost      string         `json:"shipping_cost"`
	FreeShipping      bool           `json:"free_shipping"`
	ApplyToCommission bool           `json:"apply_to_commission"`
	Notes             sql.NullString `json:"notes"`
}

type UpdateOrderRow struct {
	ID                int32          `json:"id"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	CustomerID        int32          `json:"customer_id"`
	OrderDate         time.Time      `json:"order_date"`
	Status            string         `json:"status"`
	Type              string         `json:"type"`
	Method            sql.NullString `json:"method"`
	ShipDate          time.Time      `json:"ship_date"`
	PoNumber          sql.NullString `json:"po_number"`
	ShippingCost      string         `json:"shipping_cost"`
	FreeShipping      bool           `json:"free_shipping"`
	ApplyToCommission bool           `json:"apply_to_commission"`
	Notes             sql.NullString `json:"notes"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (UpdateOrderRow, error) {
	row := q.queryRow(ctx, q.updateOrderStmt, updateOrder,
		arg.ID,
		arg.CustomerID,
		arg.OrderDate,
		arg.Status,
		arg.Type,
		arg.Method,
		arg.ShipDate,
		arg.PoNumber,
		arg.ShippingCost,
		arg.FreeShipping,
		arg.ApplyToCommission,
		arg.Notes,
	)
	var i UpdateOrderRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.OrderDate,
		&i.Status,
		&i.Type,
		&i.Method,
		&i.ShipDate,
		&i.PoNumber,
		&i.ShippingCost,
		&i.FreeShipping,
		&i.ApplyToCommission,
		&i.Notes,
	)
	return i, err
}
