-- +goose Up
ALTER TABLE products 
    ALTER COLUMN upc DROP NOT NULL,
    ALTER COLUMN cost DROP NOT NULL,
    ALTER COLUMN price DROP NOT NULL,
    ALTER COLUMN cost SET DEFAULT 0,
    ALTER COLUMN price SET DEFAULT 0;

-- +goose Down
ALTER TABLE products 
    ALTER COLUMN upc SET NOT NULL,
    ALTER COLUMN cost SET NOT NULL,
    ALTER COLUMN price SET NOT NULL,
    ALTER COLUMN cost DROP DEFAULT,
    ALTER COLUMN price DROP DEFAULT;
